// <auto-generated />
// Generated by tools/generate_csharp_binding.py. Do not edit by hand.

using System;
using NewEmoji.Native;

namespace NewEmoji;

public static class EmojiGeneratedComponents
{
    public static EmojiElement CreatePanel(this EmojiWindow window, int parentId, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var id = NativeMethods.EU_CreatePanel(window.Handle, parentId, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Panel");
    }

    public static EmojiElement AddPanel(this EmojiElement parent, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreatePanel(parent.Id, x, y, width, height);
    }

    public static EmojiElement CreateButton(this EmojiWindow window, int parentId, string emoji, string text, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var emojiBytes = NativeUtf8.GetBytes(emoji);
        var textBytes = NativeUtf8.GetBytes(text);
        var id = NativeMethods.EU_CreateButton(window.Handle, parentId, emojiBytes, emojiBytes.Length, textBytes, textBytes.Length, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Button");
    }

    public static EmojiElement AddButton(this EmojiElement parent, string emoji, string text, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateButton(parent.Id, emoji, text, x, y, width, height);
    }

    public static EmojiElement CreateEditBox(this EmojiWindow window, int parentId, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var id = NativeMethods.EU_CreateEditBox(window.Handle, parentId, x, y, width, height);
        return EmojiElement.Wrap(window, id, "EditBox");
    }

    public static EmojiElement AddEditBox(this EmojiElement parent, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateEditBox(parent.Id, x, y, width, height);
    }

    public static EmojiElement CreateInfoBox(this EmojiWindow window, int parentId, string title, string text, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var titleBytes = NativeUtf8.GetBytes(title);
        var textBytes = NativeUtf8.GetBytes(text);
        var id = NativeMethods.EU_CreateInfoBox(window.Handle, parentId, titleBytes, titleBytes.Length, textBytes, textBytes.Length, x, y, width, height);
        return EmojiElement.Wrap(window, id, "InfoBox");
    }

    public static EmojiElement AddInfoBox(this EmojiElement parent, string title, string text, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateInfoBox(parent.Id, title, text, x, y, width, height);
    }

    public static EmojiElement CreateText(this EmojiWindow window, int parentId, string text, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var textBytes = NativeUtf8.GetBytes(text);
        var id = NativeMethods.EU_CreateText(window.Handle, parentId, textBytes, textBytes.Length, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Text");
    }

    public static EmojiElement AddText(this EmojiElement parent, string text, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateText(parent.Id, text, x, y, width, height);
    }

    public static EmojiElement CreateLink(this EmojiWindow window, int parentId, string text, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var textBytes = NativeUtf8.GetBytes(text);
        var id = NativeMethods.EU_CreateLink(window.Handle, parentId, textBytes, textBytes.Length, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Link");
    }

    public static EmojiElement AddLink(this EmojiElement parent, string text, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateLink(parent.Id, text, x, y, width, height);
    }

    public static EmojiElement CreateIcon(this EmojiWindow window, int parentId, string text, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var textBytes = NativeUtf8.GetBytes(text);
        var id = NativeMethods.EU_CreateIcon(window.Handle, parentId, textBytes, textBytes.Length, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Icon");
    }

    public static EmojiElement AddIcon(this EmojiElement parent, string text, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateIcon(parent.Id, text, x, y, width, height);
    }

    public static EmojiElement CreateSpace(this EmojiWindow window, int parentId, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var id = NativeMethods.EU_CreateSpace(window.Handle, parentId, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Space");
    }

    public static EmojiElement AddSpace(this EmojiElement parent, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateSpace(parent.Id, x, y, width, height);
    }

    public static EmojiElement CreateContainer(this EmojiWindow window, int parentId, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var id = NativeMethods.EU_CreateContainer(window.Handle, parentId, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Container");
    }

    public static EmojiElement AddContainer(this EmojiElement parent, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateContainer(parent.Id, x, y, width, height);
    }

    public static EmojiElement CreateHeader(this EmojiWindow window, int parentId, string text, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var textBytes = NativeUtf8.GetBytes(text);
        var id = NativeMethods.EU_CreateHeader(window.Handle, parentId, textBytes, textBytes.Length, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Header");
    }

    public static EmojiElement AddHeader(this EmojiElement parent, string text, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateHeader(parent.Id, text, x, y, width, height);
    }

    public static EmojiElement CreateAside(this EmojiWindow window, int parentId, string text, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var textBytes = NativeUtf8.GetBytes(text);
        var id = NativeMethods.EU_CreateAside(window.Handle, parentId, textBytes, textBytes.Length, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Aside");
    }

    public static EmojiElement AddAside(this EmojiElement parent, string text, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateAside(parent.Id, text, x, y, width, height);
    }

    public static EmojiElement CreateMain(this EmojiWindow window, int parentId, string text, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var textBytes = NativeUtf8.GetBytes(text);
        var id = NativeMethods.EU_CreateMain(window.Handle, parentId, textBytes, textBytes.Length, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Main");
    }

    public static EmojiElement AddMain(this EmojiElement parent, string text, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateMain(parent.Id, text, x, y, width, height);
    }

    public static EmojiElement CreateFooter(this EmojiWindow window, int parentId, string text, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var textBytes = NativeUtf8.GetBytes(text);
        var id = NativeMethods.EU_CreateFooter(window.Handle, parentId, textBytes, textBytes.Length, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Footer");
    }

    public static EmojiElement AddFooter(this EmojiElement parent, string text, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateFooter(parent.Id, text, x, y, width, height);
    }

    public static EmojiElement CreateLayout(this EmojiWindow window, int parentId, int orientation, int gap, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var id = NativeMethods.EU_CreateLayout(window.Handle, parentId, orientation, gap, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Layout");
    }

    public static EmojiElement AddLayout(this EmojiElement parent, int orientation, int gap, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateLayout(parent.Id, orientation, gap, x, y, width, height);
    }

    public static EmojiElement CreateBorder(this EmojiWindow window, int parentId, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var id = NativeMethods.EU_CreateBorder(window.Handle, parentId, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Border");
    }

    public static EmojiElement AddBorder(this EmojiElement parent, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateBorder(parent.Id, x, y, width, height);
    }

    public static EmojiElement CreateCheckbox(this EmojiWindow window, int parentId, string text, int @checked, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var textBytes = NativeUtf8.GetBytes(text);
        var id = NativeMethods.EU_CreateCheckbox(window.Handle, parentId, textBytes, textBytes.Length, @checked, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Checkbox");
    }

    public static EmojiElement AddCheckbox(this EmojiElement parent, string text, int @checked, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateCheckbox(parent.Id, text, @checked, x, y, width, height);
    }

    public static EmojiElement CreateRadio(this EmojiWindow window, int parentId, string text, int @checked, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var textBytes = NativeUtf8.GetBytes(text);
        var id = NativeMethods.EU_CreateRadio(window.Handle, parentId, textBytes, textBytes.Length, @checked, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Radio");
    }

    public static EmojiElement AddRadio(this EmojiElement parent, string text, int @checked, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateRadio(parent.Id, text, @checked, x, y, width, height);
    }

    public static EmojiElement CreateSwitch(this EmojiWindow window, int parentId, string text, int @checked, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var textBytes = NativeUtf8.GetBytes(text);
        var id = NativeMethods.EU_CreateSwitch(window.Handle, parentId, textBytes, textBytes.Length, @checked, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Switch");
    }

    public static EmojiElement AddSwitch(this EmojiElement parent, string text, int @checked, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateSwitch(parent.Id, text, @checked, x, y, width, height);
    }

    public static EmojiElement CreateSlider(this EmojiWindow window, int parentId, string text, int min_value, int max_value, int value, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var textBytes = NativeUtf8.GetBytes(text);
        var id = NativeMethods.EU_CreateSlider(window.Handle, parentId, textBytes, textBytes.Length, min_value, max_value, value, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Slider");
    }

    public static EmojiElement AddSlider(this EmojiElement parent, string text, int min_value, int max_value, int value, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateSlider(parent.Id, text, min_value, max_value, value, x, y, width, height);
    }

    public static EmojiElement CreateInputNumber(this EmojiWindow window, int parentId, string text, int value, int min_value, int max_value, int step, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var textBytes = NativeUtf8.GetBytes(text);
        var id = NativeMethods.EU_CreateInputNumber(window.Handle, parentId, textBytes, textBytes.Length, value, min_value, max_value, step, x, y, width, height);
        return EmojiElement.Wrap(window, id, "InputNumber");
    }

    public static EmojiElement AddInputNumber(this EmojiElement parent, string text, int value, int min_value, int max_value, int step, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateInputNumber(parent.Id, text, value, min_value, max_value, step, x, y, width, height);
    }

    public static EmojiElement CreateInput(this EmojiWindow window, int parentId, string text, string placeholder, string prefix, string suffix, int clearable, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var textBytes = NativeUtf8.GetBytes(text);
        var placeholderBytes = NativeUtf8.GetBytes(placeholder);
        var prefixBytes = NativeUtf8.GetBytes(prefix);
        var suffixBytes = NativeUtf8.GetBytes(suffix);
        var id = NativeMethods.EU_CreateInput(window.Handle, parentId, textBytes, textBytes.Length, placeholderBytes, placeholderBytes.Length, prefixBytes, prefixBytes.Length, suffixBytes, suffixBytes.Length, clearable, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Input");
    }

    public static EmojiElement AddInput(this EmojiElement parent, string text, string placeholder, string prefix, string suffix, int clearable, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateInput(parent.Id, text, placeholder, prefix, suffix, clearable, x, y, width, height);
    }

    public static EmojiElement CreateInputGroup(this EmojiWindow window, int parentId, string value, string placeholder, int size, int clearable, int password, int show_word_limit, int autosize, int min_rows, int max_rows, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var valueBytes = NativeUtf8.GetBytes(value);
        var placeholderBytes = NativeUtf8.GetBytes(placeholder);
        var id = NativeMethods.EU_CreateInputGroup(window.Handle, parentId, valueBytes, valueBytes.Length, placeholderBytes, placeholderBytes.Length, size, clearable, password, show_word_limit, autosize, min_rows, max_rows, x, y, width, height);
        return EmojiElement.Wrap(window, id, "InputGroup");
    }

    public static EmojiElement AddInputGroup(this EmojiElement parent, string value, string placeholder, int size, int clearable, int password, int show_word_limit, int autosize, int min_rows, int max_rows, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateInputGroup(parent.Id, value, placeholder, size, clearable, password, show_word_limit, autosize, min_rows, max_rows, x, y, width, height);
    }

    public static EmojiElement CreateInputTag(this EmojiWindow window, int parentId, string tags, string placeholder, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var tagsBytes = NativeUtf8.GetBytes(tags);
        var placeholderBytes = NativeUtf8.GetBytes(placeholder);
        var id = NativeMethods.EU_CreateInputTag(window.Handle, parentId, tagsBytes, tagsBytes.Length, placeholderBytes, placeholderBytes.Length, x, y, width, height);
        return EmojiElement.Wrap(window, id, "InputTag");
    }

    public static EmojiElement AddInputTag(this EmojiElement parent, string tags, string placeholder, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateInputTag(parent.Id, tags, placeholder, x, y, width, height);
    }

    public static EmojiElement CreateSelect(this EmojiWindow window, int parentId, string text, string options, int selected_index, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var textBytes = NativeUtf8.GetBytes(text);
        var optionsBytes = NativeUtf8.GetBytes(options);
        var id = NativeMethods.EU_CreateSelect(window.Handle, parentId, textBytes, textBytes.Length, optionsBytes, optionsBytes.Length, selected_index, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Select");
    }

    public static EmojiElement AddSelect(this EmojiElement parent, string text, string options, int selected_index, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateSelect(parent.Id, text, options, selected_index, x, y, width, height);
    }

    public static EmojiElement CreateSelectV2(this EmojiWindow window, int parentId, string text, string options, int selected_index, int visible_count, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var textBytes = NativeUtf8.GetBytes(text);
        var optionsBytes = NativeUtf8.GetBytes(options);
        var id = NativeMethods.EU_CreateSelectV2(window.Handle, parentId, textBytes, textBytes.Length, optionsBytes, optionsBytes.Length, selected_index, visible_count, x, y, width, height);
        return EmojiElement.Wrap(window, id, "SelectV2");
    }

    public static EmojiElement AddSelectV2(this EmojiElement parent, string text, string options, int selected_index, int visible_count, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateSelectV2(parent.Id, text, options, selected_index, visible_count, x, y, width, height);
    }

    public static EmojiElement CreateRate(this EmojiWindow window, int parentId, string text, int value, int max_value, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var textBytes = NativeUtf8.GetBytes(text);
        var id = NativeMethods.EU_CreateRate(window.Handle, parentId, textBytes, textBytes.Length, value, max_value, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Rate");
    }

    public static EmojiElement AddRate(this EmojiElement parent, string text, int value, int max_value, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateRate(parent.Id, text, value, max_value, x, y, width, height);
    }

    public static EmojiElement CreateColorPicker(this EmojiWindow window, int parentId, string text, uint value, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var textBytes = NativeUtf8.GetBytes(text);
        var id = NativeMethods.EU_CreateColorPicker(window.Handle, parentId, textBytes, textBytes.Length, value, x, y, width, height);
        return EmojiElement.Wrap(window, id, "ColorPicker");
    }

    public static EmojiElement AddColorPicker(this EmojiElement parent, string text, uint value, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateColorPicker(parent.Id, text, value, x, y, width, height);
    }

    public static EmojiElement CreateTag(this EmojiWindow window, int parentId, string text, int tag_type, int effect, int closable, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var textBytes = NativeUtf8.GetBytes(text);
        var id = NativeMethods.EU_CreateTag(window.Handle, parentId, textBytes, textBytes.Length, tag_type, effect, closable, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Tag");
    }

    public static EmojiElement AddTag(this EmojiElement parent, string text, int tag_type, int effect, int closable, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateTag(parent.Id, text, tag_type, effect, closable, x, y, width, height);
    }

    public static EmojiElement CreateBadge(this EmojiWindow window, int parentId, string text, string value, int max_value, int dot, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var textBytes = NativeUtf8.GetBytes(text);
        var valueBytes = NativeUtf8.GetBytes(value);
        var id = NativeMethods.EU_CreateBadge(window.Handle, parentId, textBytes, textBytes.Length, valueBytes, valueBytes.Length, max_value, dot, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Badge");
    }

    public static EmojiElement AddBadge(this EmojiElement parent, string text, string value, int max_value, int dot, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateBadge(parent.Id, text, value, max_value, dot, x, y, width, height);
    }

    public static EmojiElement CreateProgress(this EmojiWindow window, int parentId, string text, int percentage, int status, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var textBytes = NativeUtf8.GetBytes(text);
        var id = NativeMethods.EU_CreateProgress(window.Handle, parentId, textBytes, textBytes.Length, percentage, status, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Progress");
    }

    public static EmojiElement AddProgress(this EmojiElement parent, string text, int percentage, int status, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateProgress(parent.Id, text, percentage, status, x, y, width, height);
    }

    public static EmojiElement CreateAvatar(this EmojiWindow window, int parentId, string text, int shape, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var textBytes = NativeUtf8.GetBytes(text);
        var id = NativeMethods.EU_CreateAvatar(window.Handle, parentId, textBytes, textBytes.Length, shape, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Avatar");
    }

    public static EmojiElement AddAvatar(this EmojiElement parent, string text, int shape, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateAvatar(parent.Id, text, shape, x, y, width, height);
    }

    public static EmojiElement CreateEmpty(this EmojiWindow window, int parentId, string title, string desc, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var titleBytes = NativeUtf8.GetBytes(title);
        var descBytes = NativeUtf8.GetBytes(desc);
        var id = NativeMethods.EU_CreateEmpty(window.Handle, parentId, titleBytes, titleBytes.Length, descBytes, descBytes.Length, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Empty");
    }

    public static EmojiElement AddEmpty(this EmojiElement parent, string title, string desc, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateEmpty(parent.Id, title, desc, x, y, width, height);
    }

    public static EmojiElement CreateSkeleton(this EmojiWindow window, int parentId, int rows, int animated, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var id = NativeMethods.EU_CreateSkeleton(window.Handle, parentId, rows, animated, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Skeleton");
    }

    public static EmojiElement AddSkeleton(this EmojiElement parent, int rows, int animated, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateSkeleton(parent.Id, rows, animated, x, y, width, height);
    }

    public static EmojiElement CreateDescriptions(this EmojiWindow window, int parentId, string title, string items, int columns, int bordered, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var titleBytes = NativeUtf8.GetBytes(title);
        var itemsBytes = NativeUtf8.GetBytes(items);
        var id = NativeMethods.EU_CreateDescriptions(window.Handle, parentId, titleBytes, titleBytes.Length, itemsBytes, itemsBytes.Length, columns, bordered, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Descriptions");
    }

    public static EmojiElement AddDescriptions(this EmojiElement parent, string title, string items, int columns, int bordered, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateDescriptions(parent.Id, title, items, columns, bordered, x, y, width, height);
    }

    public static EmojiElement CreateTable(this EmojiWindow window, int parentId, string columns, string rows, int striped, int bordered, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var columnsBytes = NativeUtf8.GetBytes(columns);
        var rowsBytes = NativeUtf8.GetBytes(rows);
        var id = NativeMethods.EU_CreateTable(window.Handle, parentId, columnsBytes, columnsBytes.Length, rowsBytes, rowsBytes.Length, striped, bordered, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Table");
    }

    public static EmojiElement AddTable(this EmojiElement parent, string columns, string rows, int striped, int bordered, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateTable(parent.Id, columns, rows, striped, bordered, x, y, width, height);
    }

    public static EmojiElement CreateCard(this EmojiWindow window, int parentId, string title, string body, int shadow, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var titleBytes = NativeUtf8.GetBytes(title);
        var bodyBytes = NativeUtf8.GetBytes(body);
        var id = NativeMethods.EU_CreateCard(window.Handle, parentId, titleBytes, titleBytes.Length, bodyBytes, bodyBytes.Length, shadow, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Card");
    }

    public static EmojiElement AddCard(this EmojiElement parent, string title, string body, int shadow, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateCard(parent.Id, title, body, shadow, x, y, width, height);
    }

    public static EmojiElement CreateCollapse(this EmojiWindow window, int parentId, string items, int active_index, int accordion, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var itemsBytes = NativeUtf8.GetBytes(items);
        var id = NativeMethods.EU_CreateCollapse(window.Handle, parentId, itemsBytes, itemsBytes.Length, active_index, accordion, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Collapse");
    }

    public static EmojiElement AddCollapse(this EmojiElement parent, string items, int active_index, int accordion, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateCollapse(parent.Id, items, active_index, accordion, x, y, width, height);
    }

    public static EmojiElement CreateTimeline(this EmojiWindow window, int parentId, string items, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var itemsBytes = NativeUtf8.GetBytes(items);
        var id = NativeMethods.EU_CreateTimeline(window.Handle, parentId, itemsBytes, itemsBytes.Length, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Timeline");
    }

    public static EmojiElement AddTimeline(this EmojiElement parent, string items, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateTimeline(parent.Id, items, x, y, width, height);
    }

    public static EmojiElement CreateStatistic(this EmojiWindow window, int parentId, string title, string value, string prefix, string suffix, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var titleBytes = NativeUtf8.GetBytes(title);
        var valueBytes = NativeUtf8.GetBytes(value);
        var prefixBytes = NativeUtf8.GetBytes(prefix);
        var suffixBytes = NativeUtf8.GetBytes(suffix);
        var id = NativeMethods.EU_CreateStatistic(window.Handle, parentId, titleBytes, titleBytes.Length, valueBytes, valueBytes.Length, prefixBytes, prefixBytes.Length, suffixBytes, suffixBytes.Length, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Statistic");
    }

    public static EmojiElement AddStatistic(this EmojiElement parent, string title, string value, string prefix, string suffix, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateStatistic(parent.Id, title, value, prefix, suffix, x, y, width, height);
    }

    public static EmojiElement CreateKpiCard(this EmojiWindow window, int parentId, string title, string value, string subtitle, string trend, int trend_type, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var titleBytes = NativeUtf8.GetBytes(title);
        var valueBytes = NativeUtf8.GetBytes(value);
        var subtitleBytes = NativeUtf8.GetBytes(subtitle);
        var trendBytes = NativeUtf8.GetBytes(trend);
        var id = NativeMethods.EU_CreateKpiCard(window.Handle, parentId, titleBytes, titleBytes.Length, valueBytes, valueBytes.Length, subtitleBytes, subtitleBytes.Length, trendBytes, trendBytes.Length, trend_type, x, y, width, height);
        return EmojiElement.Wrap(window, id, "KpiCard");
    }

    public static EmojiElement AddKpiCard(this EmojiElement parent, string title, string value, string subtitle, string trend, int trend_type, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateKpiCard(parent.Id, title, value, subtitle, trend, trend_type, x, y, width, height);
    }

    public static EmojiElement CreateTrend(this EmojiWindow window, int parentId, string title, string value, string percent, string detail, int direction, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var titleBytes = NativeUtf8.GetBytes(title);
        var valueBytes = NativeUtf8.GetBytes(value);
        var percentBytes = NativeUtf8.GetBytes(percent);
        var detailBytes = NativeUtf8.GetBytes(detail);
        var id = NativeMethods.EU_CreateTrend(window.Handle, parentId, titleBytes, titleBytes.Length, valueBytes, valueBytes.Length, percentBytes, percentBytes.Length, detailBytes, detailBytes.Length, direction, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Trend");
    }

    public static EmojiElement AddTrend(this EmojiElement parent, string title, string value, string percent, string detail, int direction, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateTrend(parent.Id, title, value, percent, detail, direction, x, y, width, height);
    }

    public static EmojiElement CreateStatusDot(this EmojiWindow window, int parentId, string label, string desc, int status, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var labelBytes = NativeUtf8.GetBytes(label);
        var descBytes = NativeUtf8.GetBytes(desc);
        var id = NativeMethods.EU_CreateStatusDot(window.Handle, parentId, labelBytes, labelBytes.Length, descBytes, descBytes.Length, status, x, y, width, height);
        return EmojiElement.Wrap(window, id, "StatusDot");
    }

    public static EmojiElement AddStatusDot(this EmojiElement parent, string label, string desc, int status, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateStatusDot(parent.Id, label, desc, status, x, y, width, height);
    }

    public static EmojiElement CreateGauge(this EmojiWindow window, int parentId, string title, int value, string caption, int status, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var titleBytes = NativeUtf8.GetBytes(title);
        var captionBytes = NativeUtf8.GetBytes(caption);
        var id = NativeMethods.EU_CreateGauge(window.Handle, parentId, titleBytes, titleBytes.Length, value, captionBytes, captionBytes.Length, status, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Gauge");
    }

    public static EmojiElement AddGauge(this EmojiElement parent, string title, int value, string caption, int status, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateGauge(parent.Id, title, value, caption, status, x, y, width, height);
    }

    public static EmojiElement CreateRingProgress(this EmojiWindow window, int parentId, string title, int value, string label, int status, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var titleBytes = NativeUtf8.GetBytes(title);
        var labelBytes = NativeUtf8.GetBytes(label);
        var id = NativeMethods.EU_CreateRingProgress(window.Handle, parentId, titleBytes, titleBytes.Length, value, labelBytes, labelBytes.Length, status, x, y, width, height);
        return EmojiElement.Wrap(window, id, "RingProgress");
    }

    public static EmojiElement AddRingProgress(this EmojiElement parent, string title, int value, string label, int status, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateRingProgress(parent.Id, title, value, label, status, x, y, width, height);
    }

    public static EmojiElement CreateBulletProgress(this EmojiWindow window, int parentId, string title, string desc, int value, int target, int status, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var titleBytes = NativeUtf8.GetBytes(title);
        var descBytes = NativeUtf8.GetBytes(desc);
        var id = NativeMethods.EU_CreateBulletProgress(window.Handle, parentId, titleBytes, titleBytes.Length, descBytes, descBytes.Length, value, target, status, x, y, width, height);
        return EmojiElement.Wrap(window, id, "BulletProgress");
    }

    public static EmojiElement AddBulletProgress(this EmojiElement parent, string title, string desc, int value, int target, int status, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateBulletProgress(parent.Id, title, desc, value, target, status, x, y, width, height);
    }

    public static EmojiElement CreateLineChart(this EmojiWindow window, int parentId, string title, string points, int chart_style, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var titleBytes = NativeUtf8.GetBytes(title);
        var pointsBytes = NativeUtf8.GetBytes(points);
        var id = NativeMethods.EU_CreateLineChart(window.Handle, parentId, titleBytes, titleBytes.Length, pointsBytes, pointsBytes.Length, chart_style, x, y, width, height);
        return EmojiElement.Wrap(window, id, "LineChart");
    }

    public static EmojiElement AddLineChart(this EmojiElement parent, string title, string points, int chart_style, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateLineChart(parent.Id, title, points, chart_style, x, y, width, height);
    }

    public static EmojiElement CreateBarChart(this EmojiWindow window, int parentId, string title, string bars, int orientation, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var titleBytes = NativeUtf8.GetBytes(title);
        var barsBytes = NativeUtf8.GetBytes(bars);
        var id = NativeMethods.EU_CreateBarChart(window.Handle, parentId, titleBytes, titleBytes.Length, barsBytes, barsBytes.Length, orientation, x, y, width, height);
        return EmojiElement.Wrap(window, id, "BarChart");
    }

    public static EmojiElement AddBarChart(this EmojiElement parent, string title, string bars, int orientation, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateBarChart(parent.Id, title, bars, orientation, x, y, width, height);
    }

    public static EmojiElement CreateDonutChart(this EmojiWindow window, int parentId, string title, string slices, int active_index, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var titleBytes = NativeUtf8.GetBytes(title);
        var slicesBytes = NativeUtf8.GetBytes(slices);
        var id = NativeMethods.EU_CreateDonutChart(window.Handle, parentId, titleBytes, titleBytes.Length, slicesBytes, slicesBytes.Length, active_index, x, y, width, height);
        return EmojiElement.Wrap(window, id, "DonutChart");
    }

    public static EmojiElement AddDonutChart(this EmojiElement parent, string title, string slices, int active_index, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateDonutChart(parent.Id, title, slices, active_index, x, y, width, height);
    }

    public static EmojiElement CreateDivider(this EmojiWindow window, int parentId, string text, int direction, int content_position, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var textBytes = NativeUtf8.GetBytes(text);
        var id = NativeMethods.EU_CreateDivider(window.Handle, parentId, textBytes, textBytes.Length, direction, content_position, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Divider");
    }

    public static EmojiElement AddDivider(this EmojiElement parent, string text, int direction, int content_position, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateDivider(parent.Id, text, direction, content_position, x, y, width, height);
    }

    public static EmojiElement CreateCalendar(this EmojiWindow window, int parentId, int year, int month, int selected_day, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var id = NativeMethods.EU_CreateCalendar(window.Handle, parentId, year, month, selected_day, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Calendar");
    }

    public static EmojiElement AddCalendar(this EmojiElement parent, int year, int month, int selected_day, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateCalendar(parent.Id, year, month, selected_day, x, y, width, height);
    }

    public static EmojiElement CreateTree(this EmojiWindow window, int parentId, string items, int selected_index, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var itemsBytes = NativeUtf8.GetBytes(items);
        var id = NativeMethods.EU_CreateTree(window.Handle, parentId, itemsBytes, itemsBytes.Length, selected_index, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Tree");
    }

    public static EmojiElement AddTree(this EmojiElement parent, string items, int selected_index, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateTree(parent.Id, items, selected_index, x, y, width, height);
    }

    public static EmojiElement CreateTreeSelect(this EmojiWindow window, int parentId, string items, int selected_index, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var itemsBytes = NativeUtf8.GetBytes(items);
        var id = NativeMethods.EU_CreateTreeSelect(window.Handle, parentId, itemsBytes, itemsBytes.Length, selected_index, x, y, width, height);
        return EmojiElement.Wrap(window, id, "TreeSelect");
    }

    public static EmojiElement AddTreeSelect(this EmojiElement parent, string items, int selected_index, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateTreeSelect(parent.Id, items, selected_index, x, y, width, height);
    }

    public static EmojiElement CreateTransfer(this EmojiWindow window, int parentId, string left, string right, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var leftBytes = NativeUtf8.GetBytes(left);
        var rightBytes = NativeUtf8.GetBytes(right);
        var id = NativeMethods.EU_CreateTransfer(window.Handle, parentId, leftBytes, leftBytes.Length, rightBytes, rightBytes.Length, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Transfer");
    }

    public static EmojiElement AddTransfer(this EmojiElement parent, string left, string right, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateTransfer(parent.Id, left, right, x, y, width, height);
    }

    public static EmojiElement CreateAutocomplete(this EmojiWindow window, int parentId, string value, string suggestions, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var valueBytes = NativeUtf8.GetBytes(value);
        var suggestionsBytes = NativeUtf8.GetBytes(suggestions);
        var id = NativeMethods.EU_CreateAutocomplete(window.Handle, parentId, valueBytes, valueBytes.Length, suggestionsBytes, suggestionsBytes.Length, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Autocomplete");
    }

    public static EmojiElement AddAutocomplete(this EmojiElement parent, string value, string suggestions, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateAutocomplete(parent.Id, value, suggestions, x, y, width, height);
    }

    public static EmojiElement CreateMentions(this EmojiWindow window, int parentId, string value, string suggestions, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var valueBytes = NativeUtf8.GetBytes(value);
        var suggestionsBytes = NativeUtf8.GetBytes(suggestions);
        var id = NativeMethods.EU_CreateMentions(window.Handle, parentId, valueBytes, valueBytes.Length, suggestionsBytes, suggestionsBytes.Length, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Mentions");
    }

    public static EmojiElement AddMentions(this EmojiElement parent, string value, string suggestions, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateMentions(parent.Id, value, suggestions, x, y, width, height);
    }

    public static EmojiElement CreateCascader(this EmojiWindow window, int parentId, string options, string selected, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var optionsBytes = NativeUtf8.GetBytes(options);
        var selectedBytes = NativeUtf8.GetBytes(selected);
        var id = NativeMethods.EU_CreateCascader(window.Handle, parentId, optionsBytes, optionsBytes.Length, selectedBytes, selectedBytes.Length, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Cascader");
    }

    public static EmojiElement AddCascader(this EmojiElement parent, string options, string selected, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateCascader(parent.Id, options, selected, x, y, width, height);
    }

    public static EmojiElement CreateDatePicker(this EmojiWindow window, int parentId, int year, int month, int selected_day, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var id = NativeMethods.EU_CreateDatePicker(window.Handle, parentId, year, month, selected_day, x, y, width, height);
        return EmojiElement.Wrap(window, id, "DatePicker");
    }

    public static EmojiElement AddDatePicker(this EmojiElement parent, int year, int month, int selected_day, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateDatePicker(parent.Id, year, month, selected_day, x, y, width, height);
    }

    public static EmojiElement CreateTimePicker(this EmojiWindow window, int parentId, int hour, int minute, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var id = NativeMethods.EU_CreateTimePicker(window.Handle, parentId, hour, minute, x, y, width, height);
        return EmojiElement.Wrap(window, id, "TimePicker");
    }

    public static EmojiElement AddTimePicker(this EmojiElement parent, int hour, int minute, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateTimePicker(parent.Id, hour, minute, x, y, width, height);
    }

    public static EmojiElement CreateDateTimePicker(this EmojiWindow window, int parentId, int year, int month, int day, int hour, int minute, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var id = NativeMethods.EU_CreateDateTimePicker(window.Handle, parentId, year, month, day, hour, minute, x, y, width, height);
        return EmojiElement.Wrap(window, id, "DateTimePicker");
    }

    public static EmojiElement AddDateTimePicker(this EmojiElement parent, int year, int month, int day, int hour, int minute, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateDateTimePicker(parent.Id, year, month, day, hour, minute, x, y, width, height);
    }

    public static EmojiElement CreateTimeSelect(this EmojiWindow window, int parentId, int hour, int minute, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var id = NativeMethods.EU_CreateTimeSelect(window.Handle, parentId, hour, minute, x, y, width, height);
        return EmojiElement.Wrap(window, id, "TimeSelect");
    }

    public static EmojiElement AddTimeSelect(this EmojiElement parent, int hour, int minute, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateTimeSelect(parent.Id, hour, minute, x, y, width, height);
    }

    public static EmojiElement CreateDropdown(this EmojiWindow window, int parentId, string text, string items, int selected_index, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var textBytes = NativeUtf8.GetBytes(text);
        var itemsBytes = NativeUtf8.GetBytes(items);
        var id = NativeMethods.EU_CreateDropdown(window.Handle, parentId, textBytes, textBytes.Length, itemsBytes, itemsBytes.Length, selected_index, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Dropdown");
    }

    public static EmojiElement AddDropdown(this EmojiElement parent, string text, string items, int selected_index, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateDropdown(parent.Id, text, items, selected_index, x, y, width, height);
    }

    public static EmojiElement CreateMenu(this EmojiWindow window, int parentId, string items, int active_index, int orientation, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var itemsBytes = NativeUtf8.GetBytes(items);
        var id = NativeMethods.EU_CreateMenu(window.Handle, parentId, itemsBytes, itemsBytes.Length, active_index, orientation, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Menu");
    }

    public static EmojiElement AddMenu(this EmojiElement parent, string items, int active_index, int orientation, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateMenu(parent.Id, items, active_index, orientation, x, y, width, height);
    }

    public static EmojiElement CreateAnchor(this EmojiWindow window, int parentId, string items, int active_index, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var itemsBytes = NativeUtf8.GetBytes(items);
        var id = NativeMethods.EU_CreateAnchor(window.Handle, parentId, itemsBytes, itemsBytes.Length, active_index, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Anchor");
    }

    public static EmojiElement AddAnchor(this EmojiElement parent, string items, int active_index, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateAnchor(parent.Id, items, active_index, x, y, width, height);
    }

    public static EmojiElement CreateBacktop(this EmojiWindow window, int parentId, string text, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var textBytes = NativeUtf8.GetBytes(text);
        var id = NativeMethods.EU_CreateBacktop(window.Handle, parentId, textBytes, textBytes.Length, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Backtop");
    }

    public static EmojiElement AddBacktop(this EmojiElement parent, string text, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateBacktop(parent.Id, text, x, y, width, height);
    }

    public static EmojiElement CreateSegmented(this EmojiWindow window, int parentId, string items, int active_index, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var itemsBytes = NativeUtf8.GetBytes(items);
        var id = NativeMethods.EU_CreateSegmented(window.Handle, parentId, itemsBytes, itemsBytes.Length, active_index, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Segmented");
    }

    public static EmojiElement AddSegmented(this EmojiElement parent, string items, int active_index, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateSegmented(parent.Id, items, active_index, x, y, width, height);
    }

    public static EmojiElement CreatePageHeader(this EmojiWindow window, int parentId, string title, string subtitle, string back, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var titleBytes = NativeUtf8.GetBytes(title);
        var subtitleBytes = NativeUtf8.GetBytes(subtitle);
        var backBytes = NativeUtf8.GetBytes(back);
        var id = NativeMethods.EU_CreatePageHeader(window.Handle, parentId, titleBytes, titleBytes.Length, subtitleBytes, subtitleBytes.Length, backBytes, backBytes.Length, x, y, width, height);
        return EmojiElement.Wrap(window, id, "PageHeader");
    }

    public static EmojiElement AddPageHeader(this EmojiElement parent, string title, string subtitle, string back, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreatePageHeader(parent.Id, title, subtitle, back, x, y, width, height);
    }

    public static EmojiElement CreateAffix(this EmojiWindow window, int parentId, string title, string body, int offset, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var titleBytes = NativeUtf8.GetBytes(title);
        var bodyBytes = NativeUtf8.GetBytes(body);
        var id = NativeMethods.EU_CreateAffix(window.Handle, parentId, titleBytes, titleBytes.Length, bodyBytes, bodyBytes.Length, offset, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Affix");
    }

    public static EmojiElement AddAffix(this EmojiElement parent, string title, string body, int offset, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateAffix(parent.Id, title, body, offset, x, y, width, height);
    }

    public static EmojiElement CreateWatermark(this EmojiWindow window, int parentId, string content, int gap_x, int gap_y, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var contentBytes = NativeUtf8.GetBytes(content);
        var id = NativeMethods.EU_CreateWatermark(window.Handle, parentId, contentBytes, contentBytes.Length, gap_x, gap_y, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Watermark");
    }

    public static EmojiElement AddWatermark(this EmojiElement parent, string content, int gap_x, int gap_y, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateWatermark(parent.Id, content, gap_x, gap_y, x, y, width, height);
    }

    public static EmojiElement CreateTour(this EmojiWindow window, int parentId, string steps, int active_index, int open, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var stepsBytes = NativeUtf8.GetBytes(steps);
        var id = NativeMethods.EU_CreateTour(window.Handle, parentId, stepsBytes, stepsBytes.Length, active_index, open, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Tour");
    }

    public static EmojiElement AddTour(this EmojiElement parent, string steps, int active_index, int open, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateTour(parent.Id, steps, active_index, open, x, y, width, height);
    }

    public static EmojiElement CreateImage(this EmojiWindow window, int parentId, string src, string alt, int fit, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var srcBytes = NativeUtf8.GetBytes(src);
        var altBytes = NativeUtf8.GetBytes(alt);
        var id = NativeMethods.EU_CreateImage(window.Handle, parentId, srcBytes, srcBytes.Length, altBytes, altBytes.Length, fit, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Image");
    }

    public static EmojiElement AddImage(this EmojiElement parent, string src, string alt, int fit, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateImage(parent.Id, src, alt, fit, x, y, width, height);
    }

    public static EmojiElement CreateCarousel(this EmojiWindow window, int parentId, string items, int active_index, int indicator_position, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var itemsBytes = NativeUtf8.GetBytes(items);
        var id = NativeMethods.EU_CreateCarousel(window.Handle, parentId, itemsBytes, itemsBytes.Length, active_index, indicator_position, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Carousel");
    }

    public static EmojiElement AddCarousel(this EmojiElement parent, string items, int active_index, int indicator_position, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateCarousel(parent.Id, items, active_index, indicator_position, x, y, width, height);
    }

    public static EmojiElement CreateUpload(this EmojiWindow window, int parentId, string title, string tip, string files, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var titleBytes = NativeUtf8.GetBytes(title);
        var tipBytes = NativeUtf8.GetBytes(tip);
        var filesBytes = NativeUtf8.GetBytes(files);
        var id = NativeMethods.EU_CreateUpload(window.Handle, parentId, titleBytes, titleBytes.Length, tipBytes, tipBytes.Length, filesBytes, filesBytes.Length, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Upload");
    }

    public static EmojiElement AddUpload(this EmojiElement parent, string title, string tip, string files, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateUpload(parent.Id, title, tip, files, x, y, width, height);
    }

    public static EmojiElement CreateInfiniteScroll(this EmojiWindow window, int parentId, string items, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var itemsBytes = NativeUtf8.GetBytes(items);
        var id = NativeMethods.EU_CreateInfiniteScroll(window.Handle, parentId, itemsBytes, itemsBytes.Length, x, y, width, height);
        return EmojiElement.Wrap(window, id, "InfiniteScroll");
    }

    public static EmojiElement AddInfiniteScroll(this EmojiElement parent, string items, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateInfiniteScroll(parent.Id, items, x, y, width, height);
    }

    public static EmojiElement CreateBreadcrumb(this EmojiWindow window, int parentId, string items, string separator, int current_index, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var itemsBytes = NativeUtf8.GetBytes(items);
        var separatorBytes = NativeUtf8.GetBytes(separator);
        var id = NativeMethods.EU_CreateBreadcrumb(window.Handle, parentId, itemsBytes, itemsBytes.Length, separatorBytes, separatorBytes.Length, current_index, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Breadcrumb");
    }

    public static EmojiElement AddBreadcrumb(this EmojiElement parent, string items, string separator, int current_index, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateBreadcrumb(parent.Id, items, separator, current_index, x, y, width, height);
    }

    public static EmojiElement CreateTabs(this EmojiWindow window, int parentId, string items, int active_index, int tab_type, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var itemsBytes = NativeUtf8.GetBytes(items);
        var id = NativeMethods.EU_CreateTabs(window.Handle, parentId, itemsBytes, itemsBytes.Length, active_index, tab_type, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Tabs");
    }

    public static EmojiElement AddTabs(this EmojiElement parent, string items, int active_index, int tab_type, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateTabs(parent.Id, items, active_index, tab_type, x, y, width, height);
    }

    public static EmojiElement CreatePagination(this EmojiWindow window, int parentId, int total, int page_size, int current_page, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var id = NativeMethods.EU_CreatePagination(window.Handle, parentId, total, page_size, current_page, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Pagination");
    }

    public static EmojiElement AddPagination(this EmojiElement parent, int total, int page_size, int current_page, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreatePagination(parent.Id, total, page_size, current_page, x, y, width, height);
    }

    public static EmojiElement CreateSteps(this EmojiWindow window, int parentId, string items, int active_index, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var itemsBytes = NativeUtf8.GetBytes(items);
        var id = NativeMethods.EU_CreateSteps(window.Handle, parentId, itemsBytes, itemsBytes.Length, active_index, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Steps");
    }

    public static EmojiElement AddSteps(this EmojiElement parent, string items, int active_index, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateSteps(parent.Id, items, active_index, x, y, width, height);
    }

    public static EmojiElement CreateAlert(this EmojiWindow window, int parentId, string title, string desc, int alert_type, int effect, int closable, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var titleBytes = NativeUtf8.GetBytes(title);
        var descBytes = NativeUtf8.GetBytes(desc);
        var id = NativeMethods.EU_CreateAlert(window.Handle, parentId, titleBytes, titleBytes.Length, descBytes, descBytes.Length, alert_type, effect, closable, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Alert");
    }

    public static EmojiElement AddAlert(this EmojiElement parent, string title, string desc, int alert_type, int effect, int closable, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateAlert(parent.Id, title, desc, alert_type, effect, closable, x, y, width, height);
    }

    public static EmojiElement CreateResult(this EmojiWindow window, int parentId, string title, string subtitle, int result_type, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var titleBytes = NativeUtf8.GetBytes(title);
        var subtitleBytes = NativeUtf8.GetBytes(subtitle);
        var id = NativeMethods.EU_CreateResult(window.Handle, parentId, titleBytes, titleBytes.Length, subtitleBytes, subtitleBytes.Length, result_type, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Result");
    }

    public static EmojiElement AddResult(this EmojiElement parent, string title, string subtitle, int result_type, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateResult(parent.Id, title, subtitle, result_type, x, y, width, height);
    }

    public static EmojiElement CreateNotification(this EmojiWindow window, int parentId, string title, string body, int notify_type, int closable, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var titleBytes = NativeUtf8.GetBytes(title);
        var bodyBytes = NativeUtf8.GetBytes(body);
        var id = NativeMethods.EU_CreateNotification(window.Handle, parentId, titleBytes, titleBytes.Length, bodyBytes, bodyBytes.Length, notify_type, closable, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Notification");
    }

    public static EmojiElement AddNotification(this EmojiElement parent, string title, string body, int notify_type, int closable, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateNotification(parent.Id, title, body, notify_type, closable, x, y, width, height);
    }

    public static EmojiElement CreateLoading(this EmojiWindow window, int parentId, string text, int active, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var textBytes = NativeUtf8.GetBytes(text);
        var id = NativeMethods.EU_CreateLoading(window.Handle, parentId, textBytes, textBytes.Length, active, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Loading");
    }

    public static EmojiElement AddLoading(this EmojiElement parent, string text, int active, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateLoading(parent.Id, text, active, x, y, width, height);
    }

    public static EmojiElement CreateTooltip(this EmojiWindow window, int parentId, string label, string content, int placement, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var labelBytes = NativeUtf8.GetBytes(label);
        var contentBytes = NativeUtf8.GetBytes(content);
        var id = NativeMethods.EU_CreateTooltip(window.Handle, parentId, labelBytes, labelBytes.Length, contentBytes, contentBytes.Length, placement, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Tooltip");
    }

    public static EmojiElement AddTooltip(this EmojiElement parent, string label, string content, int placement, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateTooltip(parent.Id, label, content, placement, x, y, width, height);
    }

    public static EmojiElement CreatePopover(this EmojiWindow window, int parentId, string label, string title, string content, int placement, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var labelBytes = NativeUtf8.GetBytes(label);
        var titleBytes = NativeUtf8.GetBytes(title);
        var contentBytes = NativeUtf8.GetBytes(content);
        var id = NativeMethods.EU_CreatePopover(window.Handle, parentId, labelBytes, labelBytes.Length, titleBytes, titleBytes.Length, contentBytes, contentBytes.Length, placement, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Popover");
    }

    public static EmojiElement AddPopover(this EmojiElement parent, string label, string title, string content, int placement, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreatePopover(parent.Id, label, title, content, placement, x, y, width, height);
    }

    public static EmojiElement CreatePopconfirm(this EmojiWindow window, int parentId, string label, string title, string content, string confirm, string cancel, int placement, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var labelBytes = NativeUtf8.GetBytes(label);
        var titleBytes = NativeUtf8.GetBytes(title);
        var contentBytes = NativeUtf8.GetBytes(content);
        var confirmBytes = NativeUtf8.GetBytes(confirm);
        var cancelBytes = NativeUtf8.GetBytes(cancel);
        var id = NativeMethods.EU_CreatePopconfirm(window.Handle, parentId, labelBytes, labelBytes.Length, titleBytes, titleBytes.Length, contentBytes, contentBytes.Length, confirmBytes, confirmBytes.Length, cancelBytes, cancelBytes.Length, placement, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Popconfirm");
    }

    public static EmojiElement AddPopconfirm(this EmojiElement parent, string label, string title, string content, string confirm, string cancel, int placement, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreatePopconfirm(parent.Id, label, title, content, confirm, cancel, placement, x, y, width, height);
    }

    public static EmojiElement CreateIconButton(this EmojiWindow window, int parentId, string icon, string tooltip, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var iconBytes = NativeUtf8.GetBytes(icon);
        var tooltipBytes = NativeUtf8.GetBytes(tooltip);
        var id = NativeMethods.EU_CreateIconButton(window.Handle, parentId, iconBytes, iconBytes.Length, tooltipBytes, tooltipBytes.Length, x, y, width, height);
        return EmojiElement.Wrap(window, id, "IconButton");
    }

    public static EmojiElement AddIconButton(this EmojiElement parent, string icon, string tooltip, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateIconButton(parent.Id, icon, tooltip, x, y, width, height);
    }

    public static EmojiElement CreateOmnibox(this EmojiWindow window, int parentId, string value, string placeholder, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var valueBytes = NativeUtf8.GetBytes(value);
        var placeholderBytes = NativeUtf8.GetBytes(placeholder);
        var id = NativeMethods.EU_CreateOmnibox(window.Handle, parentId, valueBytes, valueBytes.Length, placeholderBytes, placeholderBytes.Length, x, y, width, height);
        return EmojiElement.Wrap(window, id, "Omnibox");
    }

    public static EmojiElement AddOmnibox(this EmojiElement parent, string value, string placeholder, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateOmnibox(parent.Id, value, placeholder, x, y, width, height);
    }

    public static EmojiElement CreateBrowserViewport(this EmojiWindow window, int parentId, int x, int y, int width, int height)
    {
        if (window is null) throw new ArgumentNullException(nameof(window));
        var id = NativeMethods.EU_CreateBrowserViewport(window.Handle, parentId, x, y, width, height);
        return EmojiElement.Wrap(window, id, "BrowserViewport");
    }

    public static EmojiElement AddBrowserViewport(this EmojiElement parent, int x, int y, int width, int height)
    {
        if (parent is null) throw new ArgumentNullException(nameof(parent));
        return parent.Window.CreateBrowserViewport(parent.Id, x, y, width, height);
    }

}
