// <auto-generated />
// Generated by tools/generate_csharp_binding.py. Do not edit by hand.

using System;
using System.Runtime.InteropServices;

namespace NewEmoji.Native;

[UnmanagedFunctionPointer(CallingConvention.StdCall)]
public delegate void ElementClickCallback(int elementId);

[UnmanagedFunctionPointer(CallingConvention.StdCall)]
public delegate void ElementKeyCallback(int elementId, int vkCode, int keyDown, int shift, int ctrl, int alt);

[UnmanagedFunctionPointer(CallingConvention.StdCall)]
public delegate void ElementTextCallback(int elementId, IntPtr utf8, int len);

[UnmanagedFunctionPointer(CallingConvention.StdCall)]
public delegate void ElementValueCallback(int elementId, int value, int rangeStart, int rangeEnd);

[UnmanagedFunctionPointer(CallingConvention.StdCall)]
public delegate void ElementReorderCallback(int elementId, int fromIndex, int toIndex, int count);

[UnmanagedFunctionPointer(CallingConvention.StdCall)]
public delegate int ElementBeforeCloseCallback(int elementId, int action);

[UnmanagedFunctionPointer(CallingConvention.StdCall)]
public delegate int DateDisabledCallback(int elementId, int yyyymmdd);

[UnmanagedFunctionPointer(CallingConvention.StdCall)]
public delegate void TableCellCallback(int tableId, int row, int col, int action, int value);

[UnmanagedFunctionPointer(CallingConvention.StdCall)]
public delegate void TableCellEditCallback(int tableId, int row, int col, int action, IntPtr utf8, int len);

[UnmanagedFunctionPointer(CallingConvention.StdCall)]
public delegate int TableVirtualRowCallback(int tableId, int row, IntPtr buffer, int bufferSize);

[UnmanagedFunctionPointer(CallingConvention.StdCall)]
public delegate void DropdownCommandCallback(int elementId, int itemIndex, IntPtr commandUtf8, int commandLen);

[UnmanagedFunctionPointer(CallingConvention.StdCall)]
public delegate void MenuSelectCallback(int elementId, int itemIndex, IntPtr pathUtf8, int pathLen, IntPtr commandUtf8, int commandLen);

[UnmanagedFunctionPointer(CallingConvention.StdCall)]
public delegate void WindowResizeCallback(IntPtr hwnd, int width, int height);

[UnmanagedFunctionPointer(CallingConvention.StdCall)]
public delegate void WindowCloseCallback(IntPtr hwnd);

[UnmanagedFunctionPointer(CallingConvention.StdCall)]
public delegate void WindowDestroyCallback(IntPtr hwnd);

[UnmanagedFunctionPointer(CallingConvention.StdCall)]
public delegate void MessageBoxResultCallback(int messageBoxId, int result);

[UnmanagedFunctionPointer(CallingConvention.StdCall)]
public delegate void MessageBoxExCallback(int messageBoxId, int action, IntPtr valueUtf8, int valueLen);

[UnmanagedFunctionPointer(CallingConvention.StdCall)]
public delegate void TreeNodeEventCallback(int elementId, int eventCode, int itemIndex, IntPtr payloadUtf8, int payloadLen);

[UnmanagedFunctionPointer(CallingConvention.StdCall)]
public delegate int TreeNodeAllowDragCallback(int elementId, IntPtr keyUtf8, int keyLen);

[UnmanagedFunctionPointer(CallingConvention.StdCall)]
public delegate int TreeNodeAllowDropCallback(int elementId, IntPtr dragKeyUtf8, int dragKeyLen, IntPtr dropKeyUtf8, int dropKeyLen, int dropType);
